baseURL = "https://www.veterinakubinova.cz/"
languageCode = "en-us"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

[params]
  title = "Veterina Kubínová"
  metaDescription = "Veterinární ordinace s Netlify CMS a Hugo"

[languages]

  [languages.cs]
    languageName = "Čeština"
    languageCode = "cs-cz"
    contentDir = "content/cs"
    weight = 3
    mark = "CZ"

  [languages.en]
    languageName = "En"
    languageCode = "en-us"
    contentDir = "content/english"
    weight = 2
    mark = "EN"

[languages.fr]
languageName = "fr"
languageCode = "fr-fr"
contentDir = "content/fr"
weight = 2
mark = "FR"    

[taxonomies]
  category = "theme"
  scene = "scenes"
