baseURL = 'https://www.veterinakubinova.cz/'
languageCode = 'cs-cz'
defaultContentLanguage = 'cs'


[params]
  title = 'Remix, a theme for Hugo fully editable with Netlify CMS'
  metaDescription = "Hugo + Netlify CMS + One click deploy to Netlify"


# Languages
[languages.en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 2
mark = "EN"

[languages.cs]
languageName = "Čeština"
languageCode = "cs-cz"
contentDir = "content/cs"
weight = 1
mark = "CZ"


[taxonomies]
  category= "theme"
  scene = "scenes"
