baseURL = "https://www.veterinakubinova.cz/"
languageCode = "cs-cz"
defaultContentLanguage = "cs"
defaultContentLanguageInSubdir = false

[params]
  title = "Veterina Kubínová"
  metaDescription = "Veterinární ordinace s Netlify CMS a Hugo"

[languages]

  [languages.cs]
    languageName = "Čeština"
    languageCode = "cs-cz"
    contentDir = "content/fr"
    weight = 1
    mark = "CZ"

  [languages.en]
    languageName = "En"
    languageCode = "en-us"
    contentDir = "content/english"
    weight = 2
    mark = "EN"

[taxonomies]
  category = "theme"
  scene = "scenes"
