baseURL = "https://www.veterinakubinova.cz/"
languageCode = "en-us"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

[params]
  title = "Veterina Kubínová"
  metaDescription = "Veterinární ordinace s Netlify CMS a Hugo"

[languages]

  [languages.en]
    languageName = "En"
    languageCode = "en-us"
    contentDir = "content/english"
    weight = 1
    mark = "EN"
    
  [languages.cs]
    languageName = "Čeština"
    languageCode = "cs-cz"
    contentDir = "content/cs"
    weight = 2
    mark = "CZ"

  [languages.fr]
     languageName = "fr"
     languageCode = "fr-fr"
     contentDir = "content/fr"
     weight = 3
     mark = "FR"    

[taxonomies]
  category = "theme"
  scene = "scenes"
